[override]
# app, urgency
type = "app"
# required for app
name = "some_app"

[paths]
theme = "theme.toml"
# can only be specified for app
overrides = [
    "urgency/low/config.toml",
    "urgency/critical/config.toml",
]
