[override]
# app, urgency
type = "app"
# required for app
name = "some_app"

[paths]
theme = "theme.toml"
# can only be specified for app
overrides = [
    "urgency/low/config.toml",
    "urgency/critical/config.toml",
]

[events]
# on_button_left = "wmctrl -a Firefox"
# on_button_middle =
# on_button_right =
# on_notify =
# on_touch =
