
[font]
name = "Noto Sans"
size = 14.0

[colors]
background = "#285577ff"
foreground = "#ffffffff"
border = "#4c7899ff"
progress = "#5588aaff"

[layout]
width = 300
# max height
height = 100
padding = 5
margin = 10

[border]
size = 2
radius = 0

[text]
# left, center, right
alignment = "left"
# https://docs.gtk.org/Pango/pango_markup.html
summary = "<b>{summary}</b>"
body = "{body}"
# app = ""
# id = ""

[icons]
# x <= 0 -- disabled
# x > 0 -- max size
size = 64
# left, right, top, bottom
position = "left"
# XDG_ICON_THEME name or absolute root path
theme = ""

[progress]
# over, source
mode = "over"
